export type CategoryId = 'commercial' | 'awards' | 'interaction' | 'aigc';
export type ProjectImage = { src: string; alt: string; width: number; height: number };
export type Project = { slug: string; title: string; shortTitle: string; english: string; category: CategoryId; year: string; discipline: string; description: string; overview: string[]; contribution?: string; awards?: string[]; pages: number[]; accent: string; heroImage?: ProjectImage; contentImages?: ProjectImage[] };
export const projects: Project[] = [
{slug:'yangtze-brand',title:'扬子江药业集团国际化品牌视觉形象设计',shortTitle:'YANGTZE · 国际化品牌',english:'A Shared Visual Language',category:'commercial',year:'2024—2026',discipline:'全球品牌 / 视觉识别',description:'围绕龙凤环与 YANGTZE 字标，建立面向国际传播的统一品牌视觉。',overview:['项目围绕扬子江药业集团的全球统一品牌标识展开，以龙凤环与 YANGTZE 字标为核心，将中国文化意象转化为可持续延展的视觉语言。'],contribution:'本人参与品牌标识、标准制图及辅助图形设计，完成品牌视觉规范与海报、发布会场景等应用方案，建立统一的国际化视觉表达。',pages:[28,29,30,31,32,33,34,35,36],accent:'#245cab'},
{slug:'taituo-brand',title:'扬子江药业集团“泰妥妥”品牌形象设计',shortTitle:'泰妥妥 · 品牌形象',english:'A Contemporary Auspiciousness',category:'commercial',year:'2025—2026',discipline:'品牌设计 / 视觉延展',description:'以龙凤文化为视觉线索，将品牌识别延展至产品、礼盒与日常应用。',overview:['“泰妥妥”聚焦男性健康消费场景。设计以龙凤文化为线索，以龙凤呈祥连接产品识别与品牌表达，塑造具有文化辨识度的品牌形象。'],contribution:'本人参与品牌标识与产品视觉体系设计，将龙凤文化元素融入标识、包装及色彩系统，形成产品系列视觉方案与台历、礼盒等衍生设计。',pages:[19,20,21,22,23,24,25,26,27],accent:'#9c1334'},
{slug:'fuyao-identity',title:'福耀科技大学视觉形象识别系统手册',shortTitle:'福耀 · 视觉识别系统',english:'An Identity with Heart',category:'commercial',year:'2024',discipline:'品牌识别 / VI 系统',description:'从五心莲花出发，构建贯穿校园场景与日常触点的视觉识别系统。',overview:['校徽以甲骨文“心”字为灵感，将五个“心”围合为五瓣莲花，在古老字形中寄托大学的办学初心。莲花造型呼应“心若菩提”，延续“敬天爱人，止于至善”的校训。'],contribution:'本人参与校徽规范、辅助图形及品牌应用设计，梳理视觉元素的使用规则，形成 VIS 手册及校园导视、文创产品等应用方案。',pages:[11,12,13,14,15,16,17,18],accent:'#183b79'},
{slug:'fuyao-glass',title:'福耀科技大学大型琉璃艺术装置',shortTitle:'福耀 · 琉璃艺术装置',english:'Glass, Light & Possibility',category:'commercial',year:'2023—2024',discipline:'公共艺术 / 材料与光影',description:'以古法琉璃连接传统工艺与当代光影，探索公共艺术与校园空间的关系。',overview:['作品为福耀科技大学图书馆空间而设计，以古法琉璃连接校园精神、传统工艺与当代科技。琉璃莲花的色彩、厚度与纹样在数字光影中相互叠映，随着观看角度呈现持续变化的光影。'],contribution:'本人参与装置视觉概念设计，结合琉璃材质、色彩层次及数字光影推敲呈现效果，协助形成并落地校园公共艺术装置。',pages:[5,6,7,8,9,10],accent:'#207e73'},
{slug:'ejin-savorscape',title:'额吉食光 · 额济纳旗文旅伴手礼包装设计',shortTitle:'额吉食光',english:'Ejin Savorscape',category:'awards',year:'2026',discipline:'包装设计 / 文旅文创',description:'将蒙古包、旋转盲盒与地域风味结合，让打开礼盒成为一次文化探索。',overview:['以蒙古包为灵感，将旋转盲盒结构与可拆卸顶盖结合。六个独立容器对应胡杨林、居延文化、航天精神、传统民居、丝路遗产和民族舞蹈，承载额济纳当地的肉制品、乳制品与果干。','用户在旋转、对位和抽取中发现不同风味。胡杨、沙漠与地域建筑进一步转化为橙蓝插画纹样，延展至香薰、杯具、文具与出行用品。'],awards:['MUSE Design Awards 2026 · 银奖','全国大学生工业设计大赛 · 上海赛区二等奖','第14届 NCDA · 上海赛区三等奖'],pages:[38,39,40,41,42],accent:'#de831c'},
{slug:'alleyway-dreams',title:'童梦巷陌·老物疗心',shortTitle:'童梦巷陌·老物疗心',english:'Alleyway Dreams, Healing Through Old Treasures',category:'awards',year:'2026',discipline:'插画设计 / 文化叙事',description:'把北方老巷转化为温暖的想象空间，在日常物件与陪伴中讲述童年的情绪。',overview:['作品关注 6—12 岁儿童在成长与社交中的焦虑，将北方老巷化作温暖的疗愈空间。横向长卷依次展开“巷中发现”“创意时刻”和“温暖陪伴”，通过探索、表达与接纳讲述情绪变化。','开放式叙事结合和缓色调，以蓝灰平衡情绪。铁皮青蛙、竹蜻蜓、糖葫芦与旧玩具承载记忆，再延展为角色、海报、故事板和文创物件。'],awards:['米兰设计周2026中国高校设计学科师生优秀作品展 · 国家级一等奖'],pages:[43,44],accent:'#dd76a5'}
,{slug:'xiaojintuan',title:'小金团：年轻人的团体资金协作 APP',shortTitle:'小金团',english:'Group Finance for Young People',category:'interaction',year:'2025',discipline:'用户研究 / 交互设计 / 用户验证',description:'面向大学生多人消费场景，串联共同资金、智能分账、日程提醒与账单追踪。',overview:['作为“Z 世代”的核心群体，大学生在集体生活、社交消费及周期性事务中频繁面临资金分摊与协作管理问题。“小金团”面向大学生团体，整合共同资金协作、日程提醒与多平台账单分账，让多人消费中的记录、计算、提醒和结清形成完整闭环。','项目从访谈和问卷进入产品定义，再通过低保真原型、可用性测试与 A/B 测试持续优化任务管理和预算体验，提升团体协作的效率与透明度。'],contribution:'本人参与项目全流程，完成访谈提纲、用户访谈、问卷设计与数据分析，并负责产品框架、低保真与高保真原型、用户验证及最终视觉呈现。',pages:[],accent:'#6825e0',heroImage:{src:'/assets/interaction/xiaojintuan-hero.png',alt:'小金团视觉系统与高保真界面总览',width:1920,height:784},contentImages:[{src:'/assets/interaction/xiaojintuan-01.png',alt:'小金团项目概览与研究结论',width:1920,height:1000},{src:'/assets/interaction/xiaojintuan-02.png',alt:'小金团洞察转化与低保真流程',width:1920,height:1000},{src:'/assets/interaction/xiaojintuan-03.png',alt:'小金团用户验证与迭代',width:1920,height:1000},{src:'/assets/interaction/xiaojintuan-04.png',alt:'小金团高保真交互系统',width:1920,height:1030},{src:'/assets/interaction/xiaojintuan-05.png',alt:'小金团全功能高保真界面',width:1920,height:1030}]}
,{slug:'ava-view',title:'AVA-VIEW：跨文化远程互动可穿戴设备',shortTitle:'AVA-VIEW',english:'A Shared View Across Distance',category:'interaction',year:'本科课程项目',discipline:'情景设计 / 交互界面 / 概念短片',description:'用可穿戴第一视角连接现场向导与远程参与者，让跨文化交流拥有更真实的临场感。',overview:['AVA-VIEW 源于疫情时期的距离社交与跨文化交流体验。概念将可穿戴设备、第一视角摄像头、语音交互和远程视觉界面结合，让不同地区、不同文化背景的用户共享同一真实视角。','现场向导可以边行走边观察与交流，远程用户能够实时提问、选择路线并参与决策。旅行、购物和文化体验由此成为一段双方共同推进的互动过程。'],contribution:'除硬件原型制作外，本人完成产品概念、使用情景、设备形态迭代、高保真界面、手绘叙事与概念宣传短片，建立从产品构想到账户端与穿戴端协同体验的完整表达。',pages:[],accent:'#2469a7',heroImage:{src:'/assets/interaction/avaview-hero.png',alt:'AVA-VIEW 设备、远程界面与穿戴场景总览',width:1908,height:716},contentImages:[{src:'/assets/interaction/avaview-01.png',alt:'AVA-VIEW 设备形态迭代与最终结构',width:1920,height:1000},{src:'/assets/interaction/avaview-02.png',alt:'AVA-VIEW 穿戴端、移动端与桌面端高保真界面',width:1920,height:1000},{src:'/assets/interaction/avaview-03.png',alt:'AVA-VIEW 场景叙事与交互流程',width:1920,height:1000},{src:'/assets/interaction/avaview-04.png',alt:'AVA-VIEW 双端协同体验',width:1920,height:1000}]}
,{slug:'animal-farm',title:'ANIMAL FARM / 动物农场',shortTitle:'ANIMAL FARM',english:'An AI Experimental Film',category:'aigc',year:'2026',discipline:'AI 实验短片 / 全流程创作',description:'以高饱和糖果色、对称构图和动物头套营造怪诞舞台，探索从剧本到成片的 AI 协作创作。',overview:['《ANIMAL FARM》是一部以乔治·奥威尔《动物农场》为灵感的 AI 实验短片。作品以高饱和糖果色、对称构图和动物头套营造怪诞的舞台感，呈现从反抗、平等承诺到权力重演的过程。'],contribution:'本人主导概念构思与视觉方向，串联剧本、分镜与提示词、AI 关键帧及视频生成，通过持续筛选与调整，完成从剧本到成片的 AI 协作影像创作。',pages:[],accent:'#bd1f30'}
];
export const categories: {id:CategoryId;title:string;english:string;index:string;note:string}[] = [
{id:'commercial',title:'已落地商业项目',english:'COMMERCIAL',index:'01',note:'DESIGN IN PRACTICE'},
{id:'awards',title:'获奖作品',english:'AWARDED',index:'02',note:'RECOGNIZED CREATIVITY'},
{id:'interaction',title:'交互设计作品',english:'INTERACTION',index:'03',note:'RESEARCH TO EXPERIENCE'},
{id:'aigc',title:'AIGC 作品',english:'EXPLORATIONS',index:'04',note:'BEYOND THE EXPECTED'}
];
export const getProject = (slug:string) => projects.find(p=>p.slug===slug);

export const projectThumbnail = (slug:string) => slug==='animal-farm'?'/assets/animal-farm/cover.jpg':slug==='xiaojintuan'?'/assets/interaction/thumb-xiaojintuan.png':slug==='ava-view'?'/assets/interaction/thumb-avaview.png':`/assets/thumb-${slug}.webp?v=20260906-composite`;
